/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGraficas;

import Classes.Configuration;
import Classes.Jenetic;
import Classes.Point;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicTextUI;
import javax.swing.table.DefaultTableModel;
import jenetic.interfaces.UIConfiguration;

/**
 *
 * @author martasantos
 */
public class Inicial extends javax.swing.JFrame {

    private Point point;
    private Configuration config;
    private Jenetic jen;
    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
    }

    public Inicial(Point point, Configuration config) {
        this.point = point;
        this.config = config;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        alturaCenario = new javax.swing.JLabel();
        larguraCenario = new javax.swing.JLabel();
        insertAlturaCen = new javax.swing.JTextField();
        insertLarguraCen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        insertXPontoInicial = new javax.swing.JTextField();
        insertYPontoInicial = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaObstaculos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Cenario = new javax.swing.JLabel();
        pontoInicial = new javax.swing.JLabel();
        pontoFinal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        insertXPontoFinal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        insertYPontoFinal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        insertIteracoes = new javax.swing.JTextField();
        cruzamentos = new javax.swing.JLabel();
        insertCruzamentos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        insertSolucoesAleatorias = new javax.swing.JTextField();
        muta = new javax.swing.JSpinner();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        alturaCenario.setText("Altura: ");

        larguraCenario.setText("Largura:");

        insertAlturaCen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertAlturaCenActionPerformed(evt);
            }
        });

        insertLarguraCen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertLarguraCenActionPerformed(evt);
            }
        });

        jLabel3.setText("X:");

        jLabel4.setText("Y:");

        insertYPontoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertYPontoInicialActionPerformed(evt);
            }
        });

        tabelaObstaculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "X", "Y", "Largura", "Altura"
            }
        ));
        jScrollPane2.setViewportView(tabelaObstaculos);

        jLabel5.setText("Obstáculos:");

        jButton1.setText("Siga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Cenario.setText("Cenário:");

        pontoInicial.setText("Ponto Inicial:");

        pontoFinal.setText("Ponto Final:");

        jLabel9.setText("X:");

        insertXPontoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertXPontoFinalActionPerformed(evt);
            }
        });

        jLabel10.setText("Y:");

        insertYPontoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertYPontoFinalActionPerformed(evt);
            }
        });

        jLabel11.setText("Mutações: ");

        jLabel12.setText("Iterações:");

        cruzamentos.setText("Cruzamentos:");

        insertCruzamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCruzamentosActionPerformed(evt);
            }
        });

        jLabel1.setText("Nº de Soluções aleatórias:");

        insertSolucoesAleatorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertSolucoesAleatoriasActionPerformed(evt);
            }
        });

        muta.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(-0.5f), Float.valueOf(0.5f), Float.valueOf(0.1f)));
        muta.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(alturaCenario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(insertAlturaCen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(larguraCenario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(insertLarguraCen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(muta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addGap(101, 101, 101)
                        .addComponent(insertIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(insertCruzamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Cenario)
                        .addGap(105, 105, 105)
                        .addComponent(pontoInicial))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(insertXPontoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(insertYPontoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jLabel12)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cruzamentos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(insertXPontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(insertYPontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5)
                        .addGap(153, 153, 153)
                        .addComponent(pontoFinal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(insertSolucoesAleatorias, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(alturaCenario)
                                .addComponent(insertAlturaCen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(insertXPontoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cenario)
                            .addComponent(pontoInicial)
                            .addComponent(pontoFinal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(insertXPontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(insertYPontoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(insertYPontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(larguraCenario)
                            .addComponent(insertLarguraCen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(cruzamentos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertCruzamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(insertSolucoesAleatorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        insertSolucoesAleatorias.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertYPontoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertYPontoInicialActionPerformed
        
    }//GEN-LAST:event_insertYPontoInicialActionPerformed

    private Point criarPontoInicial (){
        String xPontoInicial= insertXPontoInicial.getText();
        String yPontoIncial= insertYPontoInicial.getText();
        Point pi= null;
        
        try{
            
        }catch(Exception ex){
            int xinit = Integer.parseInt(xPontoInicial);
           int yinit = Integer.parseInt(yPontoIncial);
          pi=new Point(xinit, yinit);
          config.setStart(pi);
        }
        
        return pi;      
    }

    private Point criarPontoFinal (){
        String xPontoFinal= insertXPontoFinal.getText();
        String yPontoFinal= insertYPontoFinal.getText();
       
        Point pf= null;
        
        try{
            
        }catch(Exception ex){
           int xfinal = Integer.parseInt(xPontoFinal);
           int yfinal = Integer.parseInt(yPontoFinal);
          pf=new Point(xfinal, yfinal);
          config.setEnd(pf);
        }
        return pf;
        
    }
    
    public Inicial(JLabel pontoFinal, JLabel pontoInicial) {
        this.pontoFinal = pontoFinal;
        this.pontoInicial = pontoInicial;
    }

    public JLabel getPontoFinal() {
        return pontoFinal;
    }

    public void setPontoFinal(JLabel pontoFinal) {
        this.pontoFinal = pontoFinal;
    }

    public JLabel getPontoInicial() {
        return pontoInicial;
    }

    public void setPontoInicial(JLabel pontoInicial) {
        this.pontoInicial = pontoInicial;
    }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Configuration configg = new Configuration(getWidth(),getHeight(),TratarRect(), criarPontoFinal(),criarPontoFinal());      
        int sol = Integer.parseInt(insertSolucoesAleatorias.getText());
        int cruz = Integer.parseInt(insertCruzamentos.getText());
       
        float mutacoes = Float.parseFloat((String) muta.getValue());
        int ite = Integer.parseInt(insertIteracoes.getText());
        //FALTA PEDIR A POPULAÇÃO
        Jenetic jen1=new Jenetic(POPULAÇÃO, sol, cruz, mutacoes, ite, FATORMUTACAO);
        jen.run();
        
    }//GEN-LAST:event_jButton1ActionPerformed
  private void  verificarValores(){
        String alturaCen= insertAlturaCen.getText();
        String largCen=insertLarguraCen.getText();
        String mutacoes = (String) muta.getValue();
        String cruzamentos= insertCruzamentos.getText();
        String iteracoes= insertIteracoes.getText();
        String solucoesAleatorias= insertSolucoesAleatorias.getText();
        try{
           int altura = Integer.parseInt(alturaCen);
           int largura = Integer.parseInt(largCen);
           float muta = Float.parseFloat(mutacoes);
           int cruz = Integer.parseInt(cruzamentos);
           int ite = Integer.parseInt(iteracoes);
           int sol = Integer.parseInt(solucoesAleatorias);
        }catch(Exception ex){
            System.out.println("Try Again");
        }
        
    }
    private void insertYPontoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertYPontoFinalActionPerformed
        
        
    }//GEN-LAST:event_insertYPontoFinalActionPerformed

    private void insertAlturaCenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertAlturaCenActionPerformed
        
        String alturaCen = insertAlturaCen.getText();
        int altura = Integer.parseInt(alturaCen);
        config.setHeight(altura);
         
    }//GEN-LAST:event_insertAlturaCenActionPerformed

    private void insertLarguraCenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertLarguraCenActionPerformed
        String larguraCen = insertLarguraCen.getText();
        int largura = Integer.parseInt(larguraCen);
        config.setWidth(largura);
    }//GEN-LAST:event_insertLarguraCenActionPerformed

    private void insertCruzamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCruzamentosActionPerformed
        String cruzamentos= insertCruzamentos.getText();
        int cruza = Integer.parseInt(cruzamentos);
        jen.setCrossoverSize(cruza);
    }//GEN-LAST:event_insertCruzamentosActionPerformed

    private void insertIteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertIteracoesActionPerformed
        String iteracoes= insertIteracoes.getText();
        int itera = Integer.parseInt(iteracoes);
        jen.setCrossoverSize(itera);
    }//GEN-LAST:event_insertIteracoesActionPerformed

    private void insertXPontoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertXPontoInicialActionPerformed
        
    }//GEN-LAST:event_insertXPontoInicialActionPerformed

    private void insertXPontoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertXPontoFinalActionPerformed

    }//GEN-LAST:event_insertXPontoFinalActionPerformed

    private void insertSolucoesAleatoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertSolucoesAleatoriasActionPerformed
        String solucoesAleatorias= insertSolucoesAleatorias.getText();
        int solAl = Integer.parseInt(solucoesAleatorias);
        jen.setRandomSize(solAl);
    }//GEN-LAST:event_insertSolucoesAleatoriasActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }
    
    private List<Rectangle> TratarRect(){
        List<Rectangle> obstacles = new ArrayList<>();
        JTable table = tabelaObstaculos;
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for(int i=0;i<model.getRowCount();i++){
            if((model.getValueAt(i, 0)!= null) && (model.getValueAt(i,1)!= null)&& (model.getValueAt(i,2)!= null)&& (model.getValueAt(i,3)!= null)){
                int x = (int) model.getValueAt(i, 0);
                int y = (int) model.getValueAt(i, 1);
                int width = (int) model.getValueAt(i, 2);
                int height = (int) model.getValueAt(i, 3);
            
                Rectangle rectangle = new Rectangle(x,y,width,height);
                obstacles.add(rectangle);
            }
        }
        return obstacles;
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cenario;
    private javax.swing.JLabel alturaCenario;
    private javax.swing.JLabel cruzamentos;
    private javax.swing.JTextField insertAlturaCen;
    private javax.swing.JTextField insertCruzamentos;
    private javax.swing.JTextField insertIteracoes;
    private javax.swing.JTextField insertLarguraCen;
    private javax.swing.JTextField insertSolucoesAleatorias;
    private javax.swing.JTextField insertXPontoFinal;
    private javax.swing.JTextField insertXPontoInicial;
    private javax.swing.JTextField insertYPontoFinal;
    private javax.swing.JTextField insertYPontoInicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel larguraCenario;
    private javax.swing.JSpinner muta;
    private javax.swing.JLabel pontoFinal;
    private javax.swing.JLabel pontoInicial;
    private javax.swing.JTable tabelaObstaculos;
    // End of variables declaration//GEN-END:variables
}
